### ISSUE TITLE
Hero slider: missing normal mode

### ISSUE THREAD

**Issue by KienTrong** [FameThemes/screenr#38]
Currently only full screen available : http://cl.ly/0c3A2v3m3002

**Comment by shrimp2t** [comment]
Just change default padding smaller 30%
Current css code:

``` css
.swiper-slider .swiper-slide .swiper-intro-inner {
    padding-bottom: 30%;
    padding-top: 30%;
}

```
